language: rust
rust:
- stable
- beta
- nightly
script: |
  cargo build --verbose &&
  if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
    cargo test --verbose --features unstable-filter-as-fn
  else
    cargo test --verbose
  fi
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc &&
  echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2 | sed 's/-/_/'`/index.html>" > target/doc/index.html &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
notifications:
  irc:
    channels:
    - chat.freenode.net#imag
    template:
    - "%{repository_name} (%{branch} @ %{commit} by %{author}): %{result}"
env:
  global:
  - secure: kSOuk6EPQT6knPZ5gt52YRop/n1OJ89XvPcNCUG5pnOyI/O6WuBXvwo+r7HifTOH7hOcELcoA+r6BkamRYYQHv1SQxwltqQgvJqESyVOUcZiQQiHo020xL5+07QxyKu4RGDgnJMLjBN/mJkLU3jRIHK1VewQmIoAQy0/cM/wz7MGdtXj1qCairdlq+Oe0zPL8t8NQ2GxktporJFzmOfIttkPiymh9VrRlNMH0w5E/PRBC0KcjRSbGgc/kLddLYT1OIop21JNx5UXKjJwLohVUrsikpyX48bSW2bneqLQkuOY0jPI5MVx/wDkVpa1iAGxftMXmIjRERU/wV7Bm/oUhmVDpk2CLamCtLL7oxe2CmCWIb3UgaL5G7FHJgrsv0mqakht5HxnogVsbTqbVgEBXSWRiDeSNQ1j4kH4MTKgINAEYZv2VJ0n4CW5Os/bQXjQWuv8TYMu96ptWFv5KvF1OcfZwi1KbcLzBbe6YMVqMnzqvkwmj4f6FggpSYGRuZw6XzlaqikfK8v0hWrxTzGg0fPdlQMtFADYSqcJ82wNt4yqthdMPUSWW5PA/lov+2ynULbX+kXBLthTLmC5iqvz2oaSUrNtYrZpwHi8qYoZVZfIuUZNutw3ZK3jirl2s8gQtkTXSJKOQjZwpRMmHtqgxyEG2LVezxfDSG5rCKDcxHM=
